# Generated by Django 2.0.6 on 2018-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop')], max_length=5)),
                ('time', models.DateTimeField()),
                ('call_id', models.IntegerField()),
                ('source', models.IntegerField(max_length=11)),
                ('destination', models.IntegerField(max_length=11)),
            ],
        ),
    ]
