# Generated by Django 2.0.5 on 2018-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180615_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='destination',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='register',
            name='source',
            field=models.IntegerField(max_length=9),
        ),
    ]
