# Generated by Django 2.0.5 on 2018-06-15 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180615_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='destination',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='register',
            name='source',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
