# Generated by Django 2.0.5 on 2018-06-15 17:55

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180615_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='call_code',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='destination',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='source',
            field=models.IntegerField(),
        ),
    ]
