# Generated by Django 2.0.5 on 2018-06-15 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20180615_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='call_code',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
