# Generated by Django 2.0.5 on 2018-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20180615_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='call_type',
            field=models.CharField(choices=[('start', 'Start'), ('stop', 'Stop')], max_length=5),
        ),
    ]
