# Generated by Django 2.0.5 on 2018-06-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20180615_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='call_id',
        ),
    ]
