# Generated by Django 2.0.6 on 2018-06-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180615_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='destine_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='register',
            name='source_number',
            field=models.CharField(max_length=11),
        ),
    ]
